### ISSUE TITLE
Error 500 when viewing admin/members due to missing next/config

### ISSUE THREAD

**Issue by credo-nate** [slackernews/slackernews#7]
I get Internal Server Error 500 when trying to hit `admin/members`.

```
Error: Cannot find module 'next/config'
Require stack:
- /app/.next/server/pages/admin/members.js
- /app/node_modules/next/dist/server/require.js
- /app/node_modules/next/dist/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/node_modules/next/dist/server/lib/render-server.js
- /app/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at /app/node_modules/next/dist/server/require-hook.js:110:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at 4558 (/app/.next/server/pages/admin/members.js:577:18)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at 4069 (/app/.next/server/chunks/4069.js:21:69)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at /app/.next/server/pages/admin/members.js:97:82 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/.next/server/pages/admin/members.js',
    '/app/node_modules/next/dist/server/require.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/node_modules/next/dist/server/next.js',
    '/app/node_modules/next/dist/server/lib/render-server.js',
    '/app/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}
```

Using `slackernews-web:1.0.5`

**Comment by credo-nate** [comment]
I can no longer reproduce this error.
